import {
    Store, ShoppingCart, Calculator, Truck, FileText, FileCode2, TrendingUp, Layers,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type CategoryId = 'all' | 'pazaryeri' | 'eticaret' | 'muhasebe' | 'kargo' | 'efatura' | 'xml' | 'dropshipping' | 'reklam';

export interface Integration {
    id: string;
    name: string;
    category: CategoryId;
    color: string;
    gradient: string;
    logo: string;
    desc: string;
    shortDesc: string;
    features: string[];
    stats: { users: string; syncTime: string; uptime: string };
    rating: number;
    reviews: number;
    isPopular: boolean;
    isNew: boolean;
    documentation: string;
    setupTime: string;
    price: string;
    requirements: string[];
}

export const categoryMeta: { id: CategoryId; name: string; icon: LucideIcon }[] = [
    { id: 'all', name: 'Tümü', icon: Layers },
    { id: 'pazaryeri', name: 'Pazaryerleri', icon: Store },
    { id: 'eticaret', name: 'E-ticaret', icon: ShoppingCart },
    { id: 'muhasebe', name: 'Muhasebe', icon: Calculator },
    { id: 'kargo', name: 'Kargo', icon: Truck },
    { id: 'efatura', name: 'E-Fatura', icon: FileText },
    { id: 'xml', name: 'XML', icon: FileCode2 },
    { id: 'reklam', name: 'Reklam', icon: TrendingUp },
];

export const integrations: Integration[] = [
    // Pazaryeri - Popüler
    {
        id: 'trendyol',
        name: 'Trendyol',
        category: 'pazaryeri',
        color: '#F27A1A',
        gradient: 'from-orange-500 to-orange-600',
        logo: '/images/pazaryeri/Trendyol.png',
        desc: 'Türkiye\'nin en büyük pazaryerinde otomatik ürün yükleme, stok senkronizasyonu, sipariş yönetimi ve fatura entegrasyonu. Gerçek zamanlı API bağlantısı.',
        shortDesc: 'Tam otomasyon - ürün, stok, sipariş, fatura',
        features: ['Otomatik Ürün Yükleme', 'Stok Senkronizasyonu', 'Sipariş Yönetimi', 'Fatura Entegrasyonu', 'Kampanya Yönetimi', 'Raporlama API'],
        stats: { users: '12.5K+', syncTime: '< 2 dk', uptime: '99.9%' },
        rating: 4.9,
        reviews: 2847,
        isPopular: true,
        isNew: false,
        documentation: '/docs/trendyol',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['Trendyol Satıcı Hesabı', 'API Anahtarı', 'Mağaza Onayı']
    },
    {
        id: 'hepsiburada',
        name: 'Hepsiburada',
        category: 'pazaryeri',
        color: '#FF6000',
        gradient: 'from-orange-600 to-red-500',
        logo: '/images/pazaryeri/Hepsiburada.png',
        desc: 'Hepsiburada\'da çift yönlü entegrasyon ile ürünlerinizi otomatik yönetin, siparişleri anlık çekin, stokları senkronize edin.',
        shortDesc: 'Çift yönlü anlık senkronizasyon',
        features: ['Ürün Yönetimi', 'Stok Eşitleme', 'Sipariş İmport', 'Fatura Kesimi', 'Kargo Entegrasyonu', 'İade Yönetimi'],
        stats: { users: '8.2K+', syncTime: '< 3 dk', uptime: '99.8%' },
        rating: 4.8,
        reviews: 1923,
        isPopular: true,
        isNew: false,
        documentation: '/docs/hepsiburada',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['Hepsiburada Satıcı Paneli', 'API Erişimi']
    },
    {
        id: 'amazon-tr',
        name: 'Amazon.com.tr',
        category: 'pazaryeri',
        color: '#FF9900',
        gradient: 'from-yellow-500 to-orange-500',
        logo: '/images/pazaryeri/Amazon.png',
        desc: 'Amazon Türkiye\'de global standartlarda entegrasyon. FBA (Fulfillment by Amazon) desteği, reklam API\'si ve detaylı raporlama.',
        shortDesc: 'Global standartlarda entegrasyon + FBA',
        features: ['FBA Desteği', 'Reklam API', 'Amazon Prime', 'Multi-Channel', 'A+ Content', 'Brand Analytics'],
        stats: { users: '3.1K+', syncTime: '< 5 dk', uptime: '99.9%' },
        rating: 4.9,
        reviews: 856,
        isPopular: true,
        isNew: false,
        documentation: '/docs/amazon-tr',
        setupTime: '10 dakika',
        price: 'Pro Plan',
        requirements: ['Professional Seller Account', 'MWS Access']
    },
    {
        id: 'n11',
        name: 'N11',
        category: 'pazaryeri',
        color: '#A3248C',
        gradient: 'from-purple-600 to-pink-600',
        logo: '/images/pazaryeri/N11.png',
        desc: 'N11 pazaryerinde toplu ürün yükleme, otomatik fiyatlandırma ve kampanya yönetimi. Hızlı ve güvenilir API entegrasyonu.',
        shortDesc: 'Toplu ürün yükleme & fiyat yönetimi',
        features: ['Toplu Ürün Aktarımı', 'Otomatik Fiyatlandırma', 'Kampanya Yönetimi', 'Sipariş Takibi', 'Stok Kontrolü', 'Raporlama'],
        stats: { users: '9.8K+', syncTime: '< 2 dk', uptime: '99.7%' },
        rating: 4.7,
        reviews: 1634,
        isPopular: false,
        isNew: false,
        documentation: '/docs/n11',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['N11 Mağaza Hesabı', 'API Anahtarı']
    },
    {
        id: 'ciceksepeti',
        name: 'Çiçeksepeti',
        category: 'pazaryeri',
        color: '#00C853',
        gradient: 'from-green-500 to-emerald-600',
        logo: '/images/pazaryeri/ciceksepeti.png',
        desc: 'Çiçeksepeti Marketplace entegrasyonu. Hızlı teslimat entegrasyonu, hediye paketi seçenekleri ve özel kampanya yönetimi.',
        shortDesc: 'Marketplace + Hızlı Teslimat entegrasyonu',
        features: ['Marketplace API', 'Hızlı Teslimat', 'Hediye Paketi', 'Sipariş Otomasyonu', 'Stok Yönetimi', 'Fatura Entegrasyonu'],
        stats: { users: '4.5K+', syncTime: '< 3 dk', uptime: '99.8%' },
        rating: 4.6,
        reviews: 987,
        isPopular: false,
        isNew: false,
        documentation: '/docs/ciceksepeti',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['Çiçeksepeti Satıcı Hesabı']
    },
    {
        id: 'pttavm',
        name: 'PTT AVM',
        category: 'pazaryeri',
        color: '#D4AF37',
        gradient: 'from-yellow-600 to-amber-600',
        logo: '/images/pazaryeri/Pazarama.png',
        desc: 'PTT AVM pazaryerinde yerel esnaf destekli satış. Kargo entegrasyonu ve ödeme sistemleri ile tam uyumlu çalışma.',
        shortDesc: 'Yerel esnaf dostu pazaryeri entegrasyonu',
        features: ['API Entegrasyonu', 'Kargo Takibi', 'Ödeme Sistemi', 'Sipariş Yönetimi', 'Stok Kontrolü', 'Fatura'],
        stats: { users: '2.1K+', syncTime: '< 4 dk', uptime: '99.5%' },
        rating: 4.5,
        reviews: 432,
        isPopular: false,
        isNew: false,
        documentation: '/docs/pttavm',
        setupTime: '7 dakika',
        price: 'Ücretsiz',
        requirements: ['PTT AVM Satıcı Hesabı']
    },
    // E-ticaret Altyapıları
    {
        id: 'shopify',
        name: 'Shopify',
        category: 'eticaret',
        color: '#96BF48',
        gradient: 'from-green-600 to-emerald-700',
        logo: '/images/pazaryeri/Shopify.png',
        desc: 'Shopify mağazanızı Türkiye pazaryerleriyle entegre edin. E-ihracat, global satış ve çoklu kanal yönetimi.',
        shortDesc: 'E-ihracat & Global satış entegrasyonu',
        features: ['GraphQL API', 'Multi-Channel', 'E-ihracat', 'Stok Senkronizasyonu', 'Sipariş İmport', 'Metafields Desteği'],
        stats: { users: '5.3K+', syncTime: '< 1 dk', uptime: '99.9%' },
        rating: 4.9,
        reviews: 1234,
        isPopular: true,
        isNew: false,
        documentation: '/docs/shopify',
        setupTime: '3 dakika',
        price: 'Ücretsiz',
        requirements: ['Shopify Mağazası', 'Admin API Access']
    },
    {
        id: 'woocommerce',
        name: 'WooCommerce',
        category: 'eticaret',
        color: '#96588A',
        gradient: 'from-purple-600 to-amber-700',
        logo: '/images/pazaryeri/WooCommerce.png',
        desc: 'WordPress sitenizdeki WooCommerce mağazanızı tüm pazaryerleriyle senkronize edin. Açık kaynak esneklği.',
        shortDesc: 'WordPress entegrasyonu - Açık kaynak',
        features: ['REST API', 'Webhook Desteği', 'Plugin Entegrasyonu', 'Özelleştirilebilir', 'Stok Senkronizasyonu', 'Sipariş Yönetimi'],
        stats: { users: '6.7K+', syncTime: '< 2 dk', uptime: '99.8%' },
        rating: 4.8,
        reviews: 1876,
        isPopular: true,
        isNew: false,
        documentation: '/docs/woocommerce',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['WooCommerce Kurulumu', 'API Keys']
    },
    {
        id: 'ideasoft',
        name: 'IdeaSoft',
        category: 'eticaret',
        color: '#0066CC',
        gradient: 'from-orange-600 to-amber-800',
        logo: '/images/pazaryeri/ideasoft-logo.webp',
        desc: 'IdeaSoft e-ticaret altyapısı ile Türkiye\'nin lider pazaryerleri arasında çift yönlü anlık senkronizasyon.',
        shortDesc: 'Türkiye lideri altyapı entegrasyonu',
        features: ['Tam Entegrasyon', 'Anlık Senkron', 'Özel API', 'Stok Yönetimi', 'Sipariş Aktarımı', 'Fatura'],
        stats: { users: '7.2K+', syncTime: '< 1 dk', uptime: '99.9%' },
        rating: 4.8,
        reviews: 2134,
        isPopular: true,
        isNew: false,
        documentation: '/docs/ideasoft',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['IdeaSoft Mağaza', 'API Erişimi']
    },
    {
        id: 'ticimax',
        name: 'Ticimax',
        category: 'eticaret',
        color: '#6366F1',
        gradient: 'from-amber-600 to-purple-700',
        logo: '/images/pazaryeri/ticimax.webp',
        desc: 'Ticimax altyapınızda sıfır kayıp garantisi ile stok ve sipariş yönetimi. Gerçek zamanlı senkronizasyon.',
        shortDesc: 'Sıfır kayıp garantili senkronizasyon',
        features: ['Gerçek Zamanlı', 'Stok Kontrolü', 'Sipariş Yönetimi', 'XML Çıktı', 'Fatura Entegrasyonu', 'Raporlama'],
        stats: { users: '4.8K+', syncTime: '< 2 dk', uptime: '99.8%' },
        rating: 4.7,
        reviews: 1234,
        isPopular: false,
        isNew: false,
        documentation: '/docs/ticimax',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['Ticimax Panel', 'API Bilgileri']
    },
    // Muhasebe
    {
        id: 'parasut',
        name: 'Paraşüt',
        category: 'muhasebe',
        color: '#0066FF',
        gradient: 'from-orange-500 to-amber-600',
        logo: '/images/muhasebe/parasut.png',
        desc: 'Paraşüt ile otomatik e-fatura, e-arşiv fatura ve ön muhasebe entegrasyonu. Siparişler anında faturaya dönüşür.',
        shortDesc: 'Otomatik fatura & muhasebe entegrasyonu',
        features: ['E-Fatura', 'E-Arşiv', 'Otomatik Fatura', 'Cari Yönetimi', 'Banka Entegrasyonu', 'Raporlama'],
        stats: { users: '6.1K+', syncTime: 'Anlık', uptime: '99.9%' },
        rating: 4.9,
        reviews: 2156,
        isPopular: true,
        isNew: false,
        documentation: '/docs/parasut',
        setupTime: '5 dakika',
        price: 'Ücretsiz',
        requirements: ['Paraşüt Hesabı', 'API Erişimi']
    },
    {
        id: 'birfatura',
        name: 'BirFatura',
        category: 'muhasebe',
        color: '#E11D48',
        gradient: 'from-rose-500 to-red-600',
        logo: '/images/muhasebe/birfatura.png',
        desc: 'E-ticaret odaklı fatura yönetimi. Trendyol, Hepsiburada ve diğer kanallardan gelen siparişleri tek tıkla faturalandırın.',
        shortDesc: 'E-ticaretçiler için hızlı fatura çözümü',
        features: ['E-Fatura', 'E-Arşiv', 'Kargo Entegrasyonu', 'Toplu Yazdırma', 'Sipariş Yönetimi', 'GİB Uyumluluk'],
        stats: { users: '4.5K+', syncTime: 'Anlık', uptime: '99.8%' },
        rating: 4.7,
        reviews: 1243,
        isPopular: true,
        isNew: true,
        documentation: '/docs/birfatura',
        setupTime: '3 dakika',
        price: 'Ücretsiz',
        requirements: ['BirFatura Hesabı', 'API Key']
    },
    {
        id: 'logo',
        name: 'Logo Tiger / Go',
        category: 'muhasebe',
        color: '#00A0B0',
        gradient: 'from-cyan-600 to-teal-700',
        logo: '/images/muhasebe/logo.png',
        desc: 'Logo Tiger ve Go 3 ERP sistemleriyle kurumsal entegrasyon. Stok, cari, sipariş ve fatura yönetimi.',
        shortDesc: 'Kurumsal ERP entegrasyonu',
        features: ['ERP Entegrasyonu', 'Stok Yönetimi', 'Cari Yönetimi', 'Sipariş Aktarımı', 'Fatura', 'Raporlama'],
        stats: { users: '3.4K+', syncTime: '< 5 dk', uptime: '99.7%' },
        rating: 4.8,
        reviews: 987,
        isPopular: false,
        isNew: false,
        documentation: '/docs/logo',
        setupTime: '15 dakika',
        price: 'Enterprise',
        requirements: ['Logo ERP', 'Web Servis Erişimi']
    },
    {
        id: 'edm',
        name: 'EDM Bilişim',
        category: 'muhasebe',
        color: '#2563EB',
        gradient: 'from-orange-600 to-amber-700',
        logo: '/images/muhasebe/edm.png',
        desc: 'EDM Bilişim e-fatura ve e-arşiv çözümleri. Kurumsal seviyede güvenilir ve hızlı fatura iletimi.',
        shortDesc: 'Kurumsal e-fatura entegratörü',
        features: ['E-Fatura', 'E-Arşiv', 'E-İrsaliye', 'Sınırsız Saklama', 'Hızlı İletim', '7/24 Destek'],
        stats: { users: '2.8K+', syncTime: '< 1 dk', uptime: '99.9%' },
        rating: 4.8,
        reviews: 654,
        isPopular: false,
        isNew: true,
        documentation: '/docs/edm',
        setupTime: '10 dakika',
        price: 'Kontör Bazlı',
        requirements: ['EDM Üyeliği', 'Portal Bilgileri']
    },
    {
        id: 'mikro',
        name: 'Mikro Yazılım',
        category: 'muhasebe',
        color: '#1E3A8A',
        gradient: 'from-orange-800 to-amber-900',
        logo: '/images/muhasebe/mikro.png',
        desc: 'Mikro Yazılım ERP entegrasyonu. Karmaşık stok, sipariş ve finans operasyonlarını pazaryerleriyle tam uyumlu hale getirin.',
        shortDesc: 'Güçlü ERP & muhasebe entegrasyonu',
        features: ['ERP Senkronizasyonu', 'Gelişmiş Stok Takibi', 'Sipariş Otomasyonu', 'Cari Hesap Yönetimi', 'Maliyet Analizi', 'E-Dönüşüm'],
        stats: { users: '3.1K+', syncTime: '< 3 dk', uptime: '99.8%' },
        rating: 4.7,
        reviews: 843,
        isPopular: false,
        isNew: true,
        documentation: '/docs/mikro',
        setupTime: '15 dakika',
        price: 'Enterprise',
        requirements: ['Mikro ERP Lisansı', 'SQL/API Erişimi']
    },
    {
        id: 'zirve',
        name: 'Zirve Yazılım',
        category: 'muhasebe',
        color: '#0369A1',
        gradient: 'from-sky-700 to-blue-800',
        logo: '/images/muhasebe/zirve.png',
        desc: 'Zirve Yazılım ile e-ticaret satışlarınızı doğrudan ön muhasebe ve genel muhasebe kayıtlarına aktarın.',
        shortDesc: 'Mali müşavir dostu muhasebe entegrasyonu',
        features: ['Otomatik Kayıt', 'E-Fatura Aktarımı', 'Cari Eşleştirme', 'Stok Senkronu', 'Mali Müşavir Paneli', 'Hızlı Entegrasyon'],
        stats: { users: '4.8K+', syncTime: '< 2 dk', uptime: '99.7%' },
        rating: 4.8,
        reviews: 1124,
        isPopular: false,
        isNew: true,
        documentation: '/docs/zirve',
        setupTime: '10 dakika',
        price: 'Ücretsiz',
        requirements: ['Zirve Programı', 'API Modülü']
    },
    // Kargo
    {
        id: 'yurtici',
        name: 'Yurtiçi Kargo',
        category: 'kargo',
        color: '#0047AB',
        gradient: 'from-blue-700 to-blue-900',
        logo: '/images/kargo/yurtici.png',
        desc: 'Yurtiçi Kargo entegrasyonu ile toplu barkod yazdırma, otomatik kargo fişi oluşturma ve takip numarası aktarımı.',
        shortDesc: 'Toplu barkod & otomatik takip no',
        features: ['Toplu Barkod', 'Otomatik Fiş', 'Takip No', 'Şube Yönetimi', 'Teslimat Raporu', 'İade Yönetimi'],
        stats: { users: '8.9K+', syncTime: 'Anlık', uptime: '99.8%' },
        rating: 4.7,
        reviews: 1876,
        isPopular: true,
        isNew: false,
        documentation: '/docs/yurtici',
        setupTime: '10 dakika',
        price: 'Ücretsiz',
        requirements: ['Yurtiçi Kargo Sözleşmesi', 'API Bilgileri']
    },
    {
        id: 'aras',
        name: 'Aras Kargo',
        category: 'kargo',
        color: '#E30613',
        gradient: 'from-red-600 to-red-800',
        logo: '/images/kargo/aras.png',
        desc: 'Aras Kargo entegrasyonu ile anında kargo fişi oluşturma, durum sorgulama ve teslimat takibi.',
        shortDesc: 'Anında kargo fişi & durum takibi',
        features: ['Kargo Fişi', 'Durum Sorgulama', 'Takip', 'Teslimat', 'İade', 'Raporlama'],
        stats: { users: '7.5K+', syncTime: 'Anlık', uptime: '99.7%' },
        rating: 4.6,
        reviews: 1432,
        isPopular: true,
        isNew: false,
        documentation: '/docs/aras',
        setupTime: '10 dakika',
        price: 'Ücretsiz',
        requirements: ['Aras Kargo Sözleşmesi', 'Web API Erişimi']
    },
    {
        id: 'mng',
        name: 'MNG Kargo',
        category: 'kargo',
        color: '#1E3A8A',
        gradient: 'from-blue-800 to-slate-800',
        logo: '/images/kargo/mng.png',
        desc: 'MNG Kargo ile şube teslimat, iade operasyonları ve gönderi takibi. Tam entegre kargo yönetimi.',
        shortDesc: 'Şube teslimat & iade operasyonları',
        features: ['Şube Teslimat', 'İade', 'Takip', 'Gönderi Yönetimi', 'Raporlama', 'Fiyatlandırma'],
        stats: { users: '6.2K+', syncTime: 'Anlık', uptime: '99.6%' },
        rating: 4.5,
        reviews: 1123,
        isPopular: false,
        isNew: false,
        documentation: '/docs/mng',
        setupTime: '10 dakika',
        price: 'Ücretsiz',
        requirements: ['MNG Kargo Sözleşmesi', 'API Bilgileri']
    },
    // E-Fatura
    {
        id: 'gib',
        name: 'GİB E-Fatura / E-Arşiv',
        category: 'efatura',
        color: '#1F2937',
        gradient: 'from-slate-700 to-slate-900',
        logo: '/images/muhasebe/gib.png',
        desc: 'Gelir İdaresi Başkanlığı direkt entegrasyonu. 5000/30000 TL limitli faturaları doğrudan GİB\'e iletin.',
        shortDesc: 'Direkt GİB entegrasyonu - 5K/30K',
        features: ['E-Fatura', 'E-Arşiv', 'GİB Entegrasyonu', 'Otomatik İmza', 'Raporlama', 'Mali Mühür'],
        stats: { users: '15.2K+', syncTime: '< 30 sn', uptime: '99.9%' },
        rating: 4.9,
        reviews: 3421,
        isPopular: true,
        isNew: false,
        documentation: '/docs/gib',
        setupTime: '20 dakika',
        price: 'Ücretsiz',
        requirements: ['GİB Portal Hesabı', 'Mali Mühür', 'E-Fatura Kaydı']
    },
    {
        id: 'sovos',
        name: 'Sovos (Fit Solutions)',
        category: 'efatura',
        color: '#7C3AED',
        gradient: 'from-violet-600 to-purple-700',
        logo: 'S',
        desc: 'Sovos özel entegratör üzerinden saniyeler içinde e-fatura kesme. Küresel uyumlu mali çözümler.',
        shortDesc: 'Özel entegratör - Saniyeler içinde',
        features: ['E-Fatura', 'E-Arşiv', 'E-Defter', 'E-Belge', 'Raporlama', 'Global Compliance'],
        stats: { users: '4.3K+', syncTime: '< 1 dk', uptime: '99.9%' },
        rating: 4.8,
        reviews: 876,
        isPopular: false,
        isNew: false,
        documentation: '/docs/sovos',
        setupTime: '15 dakika',
        price: 'Entegratör Ücreti',
        requirements: ['Sovos Hesabı', 'Entegratör Sözleşmesi']
    },
    // XML / Dropshipping
    {
        id: 'aktifbebek',
        name: 'Aktif Bebek',
        category: 'xml',
        color: '#EC4899',
        gradient: 'from-pink-500 to-rose-600',
        logo: 'AB',
        desc: 'Binlerce bebek ürününü kar marjı ile XML\'den çekin, otomatik güncelleme ve stok takibi.',
        shortDesc: 'Bebek ürünleri - 50K+ ürün',
        features: ['XML Ürün Çekme', 'Otomatik Güncelleme', 'Stok Takibi', 'Fiyat Yönetimi', 'Kargo Entegrasyonu', 'Raporlama'],
        stats: { users: '2.1K+', syncTime: '< 15 dk', uptime: '99.5%' },
        rating: 4.6,
        reviews: 543,
        isPopular: false,
        isNew: false,
        documentation: '/docs/aktifbebek',
        setupTime: '10 dakika',
        price: 'Komisyon Bazlı',
        requirements: ['Aktif Bebek Bayiliği', 'XML Erişimi']
    },
    {
        id: 'dropshipping',
        name: 'Genel XML Entegratör',
        category: 'xml',
        color: '#10B981',
        gradient: 'from-emerald-500 to-teal-600',
        logo: 'XML',
        desc: 'Herhangi bir XML kaynağından ürün çekme, stok ve fiyat senkronizasyonu. Özelleştirilebilir yapı.',
        shortDesc: 'Özelleştirilebilir XML entegratör',
        features: ['XML Çekme', 'Stok Senkronizasyonu', 'Fiyat Yönetimi', 'Kategori Eşleme', 'Otomatik Güncelleme', 'Multi-Source'],
        stats: { users: '5.4K+', syncTime: 'Özelleştirilebilir', uptime: '99.7%' },
        rating: 4.5,
        reviews: 876,
        isPopular: false,
        isNew: true,
        documentation: '/docs/xml',
        setupTime: '30 dakika',
        price: 'Ücretsiz',
        requirements: ['XML URL', 'Yapılandırma']
    },
];

export function getDocSlug(integration: Integration): string {
    return integration.documentation.replace('/docs/', '');
}

export function getIntegrationByDocSlug(slug: string): Integration | undefined {
    return integrations.find((i) => getDocSlug(i) === slug);
}

export const integrationDocSlugs = integrations.map(getDocSlug);
